const VISIBLE_ITEMS_MOBILE = 5;
const VISIBLE_ITEMS_DESKTOP = 7;
const MAX_WIDTH_MOBILE = 1024;
const MINUTES_IN_AN_HOUR = 60;
const NOT_SHORT_FILM = 41;

export {
  VISIBLE_ITEMS_MOBILE,
  VISIBLE_ITEMS_DESKTOP,
  MAX_WIDTH_MOBILE,
  MINUTES_IN_AN_HOUR,
  NOT_SHORT_FILM
};
